import pandas as pd
import datetime

# Load the data
df = pd.read_excel("Today_News_Beijing_Tech_20260206.xlsx")

# Generate Markdown Content
report_date = datetime.date.today().strftime("%Y-%m-%d")
md_content = f"# 🇨🇳 Beijing Tech & Infrastructure Brief\n"
md_content += f"**Date:** {report_date}\n"
md_content += f"**Focus:** AI, Computing Power, New Infrastructure\n\n"
md_content += "---\n\n"

for index, row in df.iterrows():
    title = row['Title']
    category = row['Category']
    source = row['Source']
    snippet = row['Snippet']
    
    md_content += f"### {title}\n"
    md_content += f"**Category:** {category} | **Source:** {source}\n\n"
    md_content += f"{snippet}\n\n"
    md_content += "---\n\n"

md_content += "**Generated by NanoClaw Intelligence Engine**\n"

# Write to file
output_file = "BEIJING_TECH_BRIEF_20260206.md"
with open(output_file, "w") as f:
    f.write(md_content)

print(f"Report generated: {output_file}")